TravelExpences/TravelExpences/Controllers/TripReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TravelExpences.Data;
using TravelExpences.Models;
using System.IO;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using System.Data.SqlClient;

namespace TravelExpences.Controllers
{
    public class TripReportsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TripReportsController(ApplicationDbContext context)
        {
            _context = context;
        }

        //GET: TripReports
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.TripReport.ToListAsync());
        //}

        //    }
        //    return View(await tripreport.AsNoTracking().ToListAsync());
        //}



        public IActionResult Index(string searchString)
        {
            ClaimsPrincipal currentUser = User;

            if (User.Identity.IsAuthenticated)
            {

                //var days = _context.TripReport.ToList(); // proov


                //connection
                string connectionString = @"Data Source=myawesomedatabase.database.windows.net,1433;Initial Catalog=TravelExpencesSQL;Persist Security Info=False;
                        User ID=mylogin;Password=Valiit123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";
                // kalendri paevadearv arvutus otse andmebaasist
                string sqlExpression = "SELECT  EndDate,StartDate FROM TripReport " +
                    "update TripReport set DaySum = datediff(day, TripReport.StartDate, TripReport.EndDate)";

                //arvutab hyvitust vajavad raha kalendripäeva arvust *32
                string sqlExpressionone = "update TripReport SET TripDuration = DaySum * 32";


                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    SqlCommand command = new SqlCommand(sqlExpression, connection);
                    var Nice = command.ExecuteNonQuery();

                    SqlCommand commandone = new SqlCommand(sqlExpressionone, connection);
                    var Niceone = commandone.ExecuteNonQuery();

                    //  connection.Close();
                }


                List<TripReport> TripReports = new List<TripReport>();

                if (User.IsInRole("Tehnik") || User.IsInRole("Näitleja"))
                {

                    var currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
                    TripReports = _context.TripReport
                        .Include(x => x.TripStatus)
                        .Include(x => x.User)   
                        .Where(x => Convert.ToString(x.UserId) == currentUserId)
                        .OrderByDescending(x => x.EndDate).Take(20).ToList();
       
                }

                else if (User.IsInRole("Raamatupidaja"))
                {

                    TripReports = _context.TripReport.Include(x => x.TripStatus).Include(x => x.User).Where(x => x.Id != 0).OrderByDescending(x => x.EndDate).Take(20).ToList();

                }

                else if (User.IsInRole("Haldusjuht"))
                {  

                    TripReports = _context.TripReport.Include(x => x.TripStatus).Include(x => x.User).Where(x => x.User.RoleName == "Tehnik").OrderByDescending(x => x.EndDate).Take(20).ToList();
                
                }
                else if (User.IsInRole("Näitejuht"))
                {

                    TripReports = _context.TripReport.Include(x => x.TripStatus).Include(x => x.User).Where(x => x.User.RoleName == "Näitleja").OrderByDescending(x=>x.EndDate).Take(20).ToList();
                   
                }
                else
                {
                    return RedirectToAction("Login", "Identity/Account");
                }

                if(!String.IsNullOrEmpty(searchString))
                {
                    ViewData["CurrentFilter"] = searchString;


                    TripReports = TripReports.Where(s => s.User.FullName != null && s.User.FullName.Contains(searchString) ||
                    s.StartDate.ToString().Contains(searchString)).ToList();

                }

                return View(TripReports);

            }

            else
            {
                return RedirectToAction("Login", "Identity/Account");
            } 
        }



        // GET: TripReports/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripReport = await _context.TripReport
                .Include(x => x.User)
                //.Include(x => x.Comments)
                .Include(x => x.TripStatus)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tripReport == null)
            {
                return NotFound();
            }

         

            return View(tripReport);

        }

        

        // GET: TripReports/Create
        public IActionResult Create()
        {
            string userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var user = _context.Users.Where(x => x.Id == userId).FirstOrDefault();
            ViewData["FullName"] = user.FirstName + " " + user.LastName;

            return View();
        }

        // POST: TripReports/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserName,TripReason,Destination,StartDate,EndDate,TripDuration,TransportExpenses,AccomodationExpenses,AccomodationNight,OtherExpenses,ReadyToAccept")]
        TripReport tripReport, IFormFile file)
        {

            if (file != null)
            {
                //FileStream stream = new FileStream("Picture/" + tripReport.Id + ".jpg", FileMode.Create, FileAccess.Write);
                //picture.CopyTo(stream);
                //stream.Close();

                MemoryStream stream = new MemoryStream();
                file.CopyTo(stream);

                tripReport.File = stream.ToArray();
                tripReport.FileName = file.FileName;
                tripReport.FileType = file.ContentType;
                stream.Close();

            }

            if (ModelState.IsValid)
            {
                if(User.Identity.IsAuthenticated)
                {
                    tripReport.UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                }

                TripStatus tripStatus = _context.TripStatus.Where(x => x.Name == "Avatud").FirstOrDefault();

                tripReport.TripStatusId = tripStatus.Id;


                _context.Add(tripReport);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tripReport);
        }


        public IActionResult GetImageFile(int tripreportId)
        {
            var tripreport = _context.TripReport.Find(tripreportId);
            if (tripreport.File == null || tripreport.FileType == null)
            {
                return Content("Pilti pole");
            }
            return File(tripreport.File, tripreport.FileType);
        }





        //public async Task<IActionResult> Submit (int? id)
        //    {
        //        if (id == null)
        //        {
        //            return NotFound();
        //}
        //{
        //    TripStatus tripStatus = _context.TripStatus.Where(x => x.Name == "Avatud").FirstOrDefault();

        //    tripReport.TripStatusId = tripStatus.Id;

        //        _context.Add(tripReport);
        //}



        public async Task<IActionResult> Submit(int? id)
        {

            var tripReport = await _context.TripReport
                .Include(x => x.User)
                .FirstOrDefaultAsync(m => m.Id == id);



            return View(tripReport);
        }


        [HttpPost, ActionName("Submit")]
        public async Task<IActionResult> ConfirmSubmit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripReport = await _context.TripReport
                .Include(x => x.User)
                .FirstOrDefaultAsync(m => m.Id == id);

            ViewData["FullName"] = tripReport.User.FirstName + " " + tripReport.User.LastName;

            TripStatus tripStatus = _context.TripStatus.Where(x => x.Name == "Esitatud").FirstOrDefault();

            tripReport.TripStatusId = tripStatus.Id;

            _context.Update(tripReport);
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }


        public async Task<IActionResult> Confirm(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripReport = await _context.TripReport
                .Include(x => x.User)
                .FirstOrDefaultAsync(m => m.Id == id);



            return View(tripReport);
        }


        [HttpPost, ActionName("Confirm")]
        public async Task<IActionResult> ConfirmConfirm(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripReport = await _context.TripReport
                .Include(x => x.User)
                .FirstOrDefaultAsync(m => m.Id == id);

            ViewData["FullName"] = tripReport.User.FirstName + " " + tripReport.User.LastName;

TravelExpences/TravelExpences/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Töötaja portaal</title>


    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <style>

        body {
            background-color: Azure;
        }
        img {
            
            padding-bottom: 5px;
        }
    </style>
    
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                
               
                    
                
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                    <img src="/images/Logo_color.png" style="width:28px;height:28px;">
                </a>

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Navigeeri</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Töötaja portaal</a>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li><a asp-area="" asp-controller="Home" asp-action="Index">Avaleht</a></li>*@
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Kasutajale</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Kontakt</a></li>
                    <li><a asp-area="" asp-controller="TripReports" asp-action="Index">Töölähetused</a></li>


                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p style="color:#05386b;">&copy; 2019 - Töötaja portaal</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>